language: node_js
node_js:
  - '7'
git:
  depth: 5
branches:
  only:
  - master
  - /^(\d+\.){2}\d+$/
# before_script: npm run update-version $TRAVIS_TAG -- --safe
after_success: npm run cover
before_deploy: npm run prepare-github-pages
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: alisahinozcelik@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
      repo: thalesrc/js-utils
